--FANTOMY
ALTER SESSION SET ISOLATION_LEVEL=SERIALIZABLE;
commit;
SET TRANSACTION READ WRITE NAME 'Update_Account';
SELECT SUM(ACCOUNT_BALANCE) FROM ACCOUNTS;


UPDATE ACCOUNTS SET ACCOUNT_BALANCE = ACCOUNT_BALANCE*1.5;
COMMIT;
-- NIEZATWIERDZONY ODCZYT
ALTER SESSION SET ISOLATION_LEVEL=SERIALIZABLE;

COMMIT;
SET TRANSACTION READ WRITE NAME 'Create_Account';
UPDATE ACCOUNTS SET ACCOUNT_BALANCE=3000 WHERE ACCOUNT_NUMBER=1110002;

ROLLBACK;

-- NIEPOWTARZALNY ODCZYT
COMMIT;
SET TRANSACTION READ WRITE NAME 'Update_Account';
SELECT ACCOUNT_BALANCE FROM ACCOUNTS WHERE ACCOUNT_NUMBER=1110002;
UPDATE ACCOUNTS SET ACCOUNT_BALANCE=3000 WHERE ACCOUNT_NUMBER=1110002;
COMMIT;
SELECT ACCOUNT_BALANCE FROM ACCOUNTS WHERE ACCOUNT_NUMBER=1110002;