--FANTOMY
ALTER SESSION SET ISOLATION_LEVEL=SERIALIZABLE;
COMMIT;
SET TRANSACTION READ WRITE NAME 'Update_Account';
SELECT SUM(ACCOUNT_BALANCE) FROM ACCOUNTS;
INSERT INTO ACCOUNTS (ACCOUNT_NUMBER, ACCOUNT_BALANCE) VALUES (SEQ_ACCOUNT_NUMBER.NEXTVAL, 10000);
COMMIT;


-- NIEZATWIERDZONY ODCZYT
ALTER SESSION SET ISOLATION_LEVEL=SERIALIZABLE;
COMMIT;

SET TRANSACTION READ ONLY NAME 'Balances';

SELECT ACCOUNT_BALANCE FROM ACCOUNTS WHERE ACCOUNT_NUMBER=1110002;


--NIEPOWTARZALNY ODCZYT
COMMIT;
SET TRANSACTION READ WRITE NAME 'Read_Balace';
SELECT ACCOUNT_BALANCE FROM ACCOUNTS WHERE ACCOUNT_NUMBER=1110002;

SELECT ACCOUNT_BALANCE FROM ACCOUNTS WHERE ACCOUNT_NUMBER=1110002;